use_frameworks!

platform :ios, '9.0'

target 'MycocoapodsLibrary_Example' do
  pod 'MycocoapodsLibrary', :path => '../'

  target 'MycocoapodsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
